# Playbook pour récupérer le start_port
---
- name: Get start port from inventory file
  hosts: localhost
  tasks:
    - name: Read start port from inventory file
      command: "awk -F'=' '/\\[{{ wlx_application_name }}\\]/{p=1} p && /^start_port/{print $2; exit}' {{ ports_inventory }}"
      register: start_port_result

    - set_fact:
        WLB_HTTP_PORT: "{{ start_port_result.stdout | int }}"
        WLB_HTTP_PORT_PLUS_ONE: "{{ start_port_result.stdout | int + 1 }}"
